import type { Cub, GrowthCategory, TaskStatus } from "@/generated/prisma/client";
import { getWeekEnd, getWeekStart } from "@/lib/council-day";
import { db } from "@/lib/db";
import {
  ALL_GROWTH_CATEGORIES,
  GROWTH_CATEGORY_LABELS,
  growthCategoryShortLabel,
} from "@/lib/task-categories";

export { ALL_GROWTH_CATEGORIES, GROWTH_CATEGORY_LABELS, growthCategoryShortLabel };

const ACTIVE_FOCUS_STATUSES: TaskStatus[] = [
  "CLAIMED",
  "IN_PROGRESS",
  "SUBMITTED",
];

export function parseRequiredGrowthCategories(cub: Cub): GrowthCategory[] {
  if (!Array.isArray(cub.requiredGrowthCategories)) {
    return [...ALL_GROWTH_CATEGORIES];
  }

  const parsed = cub.requiredGrowthCategories.filter((value): value is GrowthCategory =>
    ALL_GROWTH_CATEGORIES.includes(value as GrowthCategory),
  );

  return parsed.length > 0 ? parsed : [...ALL_GROWTH_CATEGORIES];
}

export function growthCategoryOptionsForCub(cub: Cub) {
  return parseRequiredGrowthCategories(cub).map((value) => ({
    value,
    label: GROWTH_CATEGORY_LABELS[value],
  }));
}

export async function getCompletedGrowthCategoriesThisWeek(
  cubId: string,
  weekStartsOn = getWeekStart(),
): Promise<GrowthCategory[]> {
  const weekEnd = getWeekEnd(weekStartsOn);

  const tasks = await db.task.findMany({
    where: {
      cubId,
      category: "FOCUS_BLOCK",
      status: { in: ["COMPLETED", "APPROVED"] },
      growthCategory: { not: null },
      reviewedAt: {
        gte: weekStartsOn,
        lt: weekEnd,
      },
    },
    select: { growthCategory: true },
  });

  return [
    ...new Set(
      tasks
        .map((task) => task.growthCategory)
        .filter((value): value is GrowthCategory => value != null),
    ),
  ];
}

export async function getActiveFocusBlockByArea(
  cubId: string,
): Promise<Partial<Record<GrowthCategory, { id: string; title: string; status: TaskStatus }>>> {
  const tasks = await db.task.findMany({
    where: {
      cubId,
      category: "FOCUS_BLOCK",
      status: { in: ACTIVE_FOCUS_STATUSES },
      growthCategory: { not: null },
    },
    select: {
      id: true,
      title: true,
      status: true,
      growthCategory: true,
    },
    orderBy: { updatedAt: "desc" },
  });

  const map: Partial<
    Record<GrowthCategory, { id: string; title: string; status: TaskStatus }>
  > = {};

  for (const task of tasks) {
    if (!task.growthCategory || map[task.growthCategory]) continue;
    map[task.growthCategory] = {
      id: task.id,
      title: task.title,
      status: task.status,
    };
  }

  return map;
}

export type FocusAreaClaimEligibility = {
  canClaim: boolean;
  needsSwap: boolean;
  reason?: "active" | "completed" | "spread";
  activeTask?: { id: string; title: string; status: TaskStatus };
};

export async function getFocusAreaClaimEligibility(
  cub: Cub,
  area: GrowthCategory,
  weekStartsOn = getWeekStart(),
): Promise<FocusAreaClaimEligibility> {
  const [activeByArea, completed, pickerAvailable] = await Promise.all([
    getActiveFocusBlockByArea(cub.id),
    getCompletedGrowthCategoriesThisWeek(cub.id, weekStartsOn),
    getAvailableGrowthCategoriesForCub(cub, weekStartsOn),
  ]);

  const active = activeByArea[area];
  if (active) {
    return { canClaim: false, needsSwap: false, reason: "active", activeTask: active };
  }

  const required = parseRequiredGrowthCategories(cub);
  const isRequired = required.includes(area);

  if (completed.includes(area)) {
    if ((cub.focusAreaSwapCredits ?? 0) > 0) {
      return { canClaim: true, needsSwap: true };
    }
    return { canClaim: false, needsSwap: true, reason: "completed" };
  }

  if (isRequired && !pickerAvailable.includes(area)) {
    if ((cub.focusAreaSwapCredits ?? 0) > 0) {
      return { canClaim: true, needsSwap: true };
    }
    return { canClaim: false, needsSwap: false, reason: "spread" };
  }

  return { canClaim: true, needsSwap: false };
}

export async function getAvailableGrowthCategoriesForCub(
  cub: Cub,
  weekStartsOn = getWeekStart(),
): Promise<GrowthCategory[]> {
  const required = parseRequiredGrowthCategories(cub);
  const completed = await getCompletedGrowthCategoriesThisWeek(cub.id, weekStartsOn);
  return required.filter((category) => !completed.includes(category));
}

export function formatGrowthWeekProgress(
  completed: GrowthCategory[],
  required: GrowthCategory[],
): string {
  return `${completed.length}/${required.length} growth areas this week`;
}

export function focusBlockRewardMultiplier(requiredCount: number): number {
  return requiredCount > 0 ? 1 / requiredCount : 1;
}

const AUTO_FOCUS_SESSION_PREFIX = "Focus — ";

export function isAutoGeneratedFocusSession(task: {
  title: string;
  templateId?: string | null;
  category: string;
}): boolean {
  if (task.category !== "FOCUS_BLOCK" || task.templateId) {
    return false;
  }

  return ALL_GROWTH_CATEGORIES.some(
    (area) => task.title === `${AUTO_FOCUS_SESSION_PREFIX}${growthCategoryShortLabel(area)}`,
  );
}
