"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import type { ActionState } from "@/lib/actions/auth";
import { cubRewardFields } from "@/lib/cub-task-fields";
import { requireCubForUser } from "@/lib/cub-access";
import { db } from "@/lib/db";
import {
  getFocusAreaClaimEligibility,
  growthCategoryShortLabel,
  isAutoGeneratedFocusSession,
} from "@/lib/focus-growth";
import { syncGuardianNudgesForFamily } from "@/lib/guardian-nudges/sync";
import { logTaskFocusSession } from "@/lib/focus-session";
import { categoryRewardFields } from "@/lib/template-task-fields";
import { getCategorySuggestions } from "@/lib/task-categories";
import { cubProgressPath } from "@/lib/cub-progress-paths";
import { requireFamilyForUser, requireUserId } from "@/lib/session";

const growthCategorySchema = z.enum([
  "CHARACTER",
  "WELLNESS",
  "CREATIVITY",
  "RESPONSIBILITY",
  "COMMUNITY",
]);

function revalidateCubGrowthPaths(cubId: string, taskId?: string) {
  revalidatePath(`/cub/${cubId}`);
  revalidatePath(`/cub/${cubId}/tasks`);
  revalidatePath(cubProgressPath(cubId));
  revalidatePath(`/cub/${cubId}/rewards`);
  revalidatePath("/dashboard");
  revalidatePath("/dashboard/tasks");
  revalidatePath(`/dashboard/cubs/${cubId}/tasks`);
  revalidatePath(`/dashboard/cubs/${cubId}/progress`);
  if (taskId) {
    revalidatePath(`/dashboard/tasks/${taskId}`);
  }
}

type FocusSessionTaskRef = {
  id: string;
  title: string;
  templateId: string | null;
  category: string;
};

async function endFocusSessionForTask(task: FocusSessionTaskRef) {
  if (isAutoGeneratedFocusSession(task)) {
    await db.task.delete({ where: { id: task.id } });
    return;
  }

  await db.task.update({
    where: { id: task.id },
    data: {
      status: "AVAILABLE",
      cubId: null,
      claimedAt: null,
      startedAt: null,
      focusSessionStartedAt: null,
    },
  });
}

const activeFocusSessionSelect = {
  id: true,
  title: true,
  templateId: true,
  category: true,
  cubId: true,
  focusSessionStartedAt: true,
  growthCategory: true,
} as const;

async function requireCubActor(cubId: string) {
  const userId = await requireUserId();
  const { cub, familyId } = await requireCubForUser(cubId, userId);
  return { userId, cub, familyId };
}

async function consumeSwapCreditIfNeeded(
  cubId: string,
  needsSwap: boolean,
  currentCredits: number,
) {
  if (!needsSwap) return;
  if (currentCredits < 1) {
    throw new Error("You need a Focus area swap from the reward store.");
  }
  await db.cub.update({
    where: { id: cubId },
    data: { focusAreaSwapCredits: { decrement: 1 } },
  });
}

function focusBlockDefaults(area: z.infer<typeof growthCategorySchema>) {
  const suggested = getCategorySuggestions("FOCUS_BLOCK", { growthCategory: area });
  return {
    proofType: suggested.proofType,
    proofPrompt: suggested.proofPrompt,
    proofChecklistItems: suggested.proofChecklistItems,
    ...categoryRewardFields("FOCUS_BLOCK", { growthCategory: area }),
  };
}

export async function claimFocusBlockSessionAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const cubId = formData.get("cubId")?.toString();
  const parsedArea = growthCategorySchema.safeParse(formData.get("growthCategory"));
  const confirmSwap = formData.get("confirmSwap") === "true";

  if (!cubId || !parsedArea.success) {
    return { error: "Invalid focus session request." };
  }

  const { cub, familyId } = await requireCubActor(cubId);
  const area = parsedArea.data;
  const eligibility = await getFocusAreaClaimEligibility(cub, area);

  if (!eligibility.canClaim) {
    if (eligibility.reason === "active" && eligibility.activeTask) {
      return {
        error: `You already have a focus session for ${growthCategoryShortLabel(area)}. Finish it first.`,
      };
    }
    if (eligibility.reason === "completed" || eligibility.needsSwap) {
      return {
        error: `You already finished ${growthCategoryShortLabel(area)} this week. Ask your parent to redeem a Focus area swap, or pick another area.`,
      };
    }
    return {
      error: "Spread your focus across other growth areas first, or use a swap from the reward store.",
    };
  }

  if (eligibility.needsSwap && !confirmSwap) {
    return {
      error: `This uses 1 Focus area swap (${cub.focusAreaSwapCredits ?? 0} available). Confirm to continue.`,
    };
  }

  await consumeSwapCreditIfNeeded(
    cub.id,
    eligibility.needsSwap,
    cub.focusAreaSwapCredits ?? 0,
  );

  const task = await db.task.create({
    data: {
      familyId,
      cubId: cub.id,
      category: "FOCUS_BLOCK",
      title: `Focus — ${growthCategoryShortLabel(area)}`,
      growthCategory: area,
      status: "IN_PROGRESS",
      claimedAt: new Date(),
      startedAt: new Date(),
      focusSessionStartedAt: new Date(),
      ...focusBlockDefaults(area),
      ...cubRewardFields(cub),
    },
  });

  await syncGuardianNudgesForFamily(familyId);
  revalidateCubGrowthPaths(cub.id);
  redirect(`/cub/${cub.id}/tasks`);
}

export async function claimFocusBlockTemplateAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const cubId = formData.get("cubId")?.toString();
  const taskId = formData.get("taskId")?.toString();
  const parsedArea = growthCategorySchema.safeParse(formData.get("growthCategory"));
  const confirmSwap = formData.get("confirmSwap") === "true";

  if (!cubId || !taskId) {
    return { error: "Invalid focus block request." };
  }

  const { cub, familyId } = await requireCubActor(cubId);

  const task = await db.task.findFirst({
    where: {
      id: taskId,
      familyId,
      status: "AVAILABLE",
      category: "FOCUS_BLOCK",
    },
  });

  if (!task) {
    return { error: "This focus block is no longer available." };
  }

  const area = task.growthCategory ?? parsedArea.data;
  if (!area) {
    return { error: "Pick a growth area for this focus block." };
  }

  const eligibility = await getFocusAreaClaimEligibility(cub, area);
  if (!eligibility.canClaim) {
    if (eligibility.reason === "active") {
      return { error: "You already have an active focus session in this area." };
    }
    return {
      error: "You cannot start this focus block right now. Try another area or use a swap.",
    };
  }

  if (eligibility.needsSwap && !confirmSwap) {
    return {
      error: `This uses 1 Focus area swap (${cub.focusAreaSwapCredits ?? 0} available). Confirm to continue.`,
    };
  }

  await consumeSwapCreditIfNeeded(
    cub.id,
    eligibility.needsSwap,
    cub.focusAreaSwapCredits ?? 0,
  );

  await db.task.update({
    where: { id: task.id },
    data: {
      status: "IN_PROGRESS",
      cubId: cub.id,
      claimedAt: new Date(),
      startedAt: new Date(),
      focusSessionStartedAt: new Date(),
      growthCategory: area,
      ...cubRewardFields(cub),
    },
  });

  await syncGuardianNudgesForFamily(familyId);
  revalidateCubGrowthPaths(cub.id);
  redirect(`/cub/${cub.id}/tasks`);
}

export async function cancelFocusSessionAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const cubId = formData.get("cubId")?.toString();
  const taskId = formData.get("taskId")?.toString();

  if (!cubId || !taskId) {
    return { error: "Invalid focus session request." };
  }

  const { cub, familyId } = await requireCubActor(cubId);

  const task = await db.task.findFirst({
    where: {
      id: taskId,
      familyId,
      cubId: cub.id,
      category: "FOCUS_BLOCK",
      status: { in: ["CLAIMED", "IN_PROGRESS"] },
    },
    select: activeFocusSessionSelect,
  });

  if (!task) {
    return { error: "This focus session cannot be ended right now." };
  }

  if (task.focusSessionStartedAt) {
    await logTaskFocusSession(task, { attemptLabel: "Session ended" });
  }

  await endFocusSessionForTask(task);

  await syncGuardianNudgesForFamily(familyId);
  revalidateCubGrowthPaths(cub.id, task.id);
  return { success: "Focus session ended." };
}

export async function parentPauseFocusSessionAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const taskId = formData.get("taskId")?.toString();
  if (!taskId) {
    return { error: "Invalid focus session request." };
  }

  const userId = await requireUserId();
  const family = await requireFamilyForUser(userId);

  const task = await db.task.findFirst({
    where: {
      id: taskId,
      familyId: family.id,
      category: "FOCUS_BLOCK",
      status: "IN_PROGRESS",
      focusSessionStartedAt: { not: null },
    },
    select: activeFocusSessionSelect,
  });

  if (!task || !task.cubId) {
    return { error: "No active request timer to pause." };
  }

  await db.$transaction(async (tx) => {
    await logTaskFocusSession(task, {
      attemptLabel: "Instructions paused (parent)",
      client: tx,
    });
    await tx.task.update({
      where: { id: task.id },
      data: { focusSessionStartedAt: null },
    });
  });

  await syncGuardianNudgesForFamily(family.id);
  revalidateCubGrowthPaths(task.cubId, task.id);
  return { success: "Request timer paused. Your Cub can open instructions again to restart it." };
}

export async function parentEndFocusSessionAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const taskId = formData.get("taskId")?.toString();
  if (!taskId) {
    return { error: "Invalid focus session request." };
  }

  const userId = await requireUserId();
  const family = await requireFamilyForUser(userId);

  const task = await db.task.findFirst({
    where: {
      id: taskId,
      familyId: family.id,
      category: "FOCUS_BLOCK",
      status: { in: ["CLAIMED", "IN_PROGRESS"] },
    },
    select: activeFocusSessionSelect,
  });

  if (!task || !task.cubId) {
    return { error: "This focus session cannot be removed right now." };
  }

  if (task.focusSessionStartedAt) {
    await logTaskFocusSession(task, { attemptLabel: "Session ended (parent)" });
  }

  const removedAutoSession = isAutoGeneratedFocusSession(task);
  await endFocusSessionForTask(task);

  await syncGuardianNudgesForFamily(family.id);
  revalidateCubGrowthPaths(task.cubId, task.id);

  if (removedAutoSession) {
    redirect("/dashboard/tasks");
  }

  return { success: "Focus session removed." };
}

export async function parentPauseFocusSessionFormAction(formData: FormData): Promise<void> {
  await parentPauseFocusSessionAction({} as ActionState, formData);
}

export async function parentEndFocusSessionFormAction(formData: FormData): Promise<void> {
  await parentEndFocusSessionAction({} as ActionState, formData);
}
