-- Per-Cub caps and supervision
ALTER TABLE "Cub" ADD COLUMN IF NOT EXISTS "dailyPhoneCapMinutes" INTEGER NOT NULL DEFAULT 45;
ALTER TABLE "Cub" ADD COLUMN IF NOT EXISTS "weekendBankCapMinutes" INTEGER NOT NULL DEFAULT 90;
ALTER TABLE "Cub" ADD COLUMN IF NOT EXISTS "exchangeFocusMinutes" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Cub" ADD COLUMN IF NOT EXISTS "exchangePhoneMinutes" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Cub" ADD COLUMN IF NOT EXISTS "supervisionLevel" "SupervisionLevel" NOT NULL DEFAULT 'NEARBY';

ALTER TABLE "Cub" DROP COLUMN IF EXISTS "suggestedXp";
ALTER TABLE "Cub" DROP COLUMN IF EXISTS "suggestedFocusTokens";
ALTER TABLE "Cub" DROP COLUMN IF EXISTS "suggestedPhoneMinutes";
